    /*
     * This Java source file was generated by the Gradle 'init' task.
     */
    package oo;

    public class App {
        public String getGreeting() {
            return "Hello World!";
        }

        public static void main(String[] args) {
            var square1 = new Square1();
            var square11 = new Square1(1200, 30);
            square1.setSide(12);
            printSquareData(square1);
            printSquareData(square11);
            print(square1);
            print(square11);


           var square2 = new Square2();
           square2.setSide(10);
           printSquareData(square2);

           Square2 square21 = new Square2();
           square21.setSide(20);
           square21.getTriplePerimeter();

           var rectangle = new Rectangle();
           print(rectangle);

            var circle= new Circle();
            print(circle);

        }


        private static void printSquareData(Square square) {
            System.out.println("Square version " + Square1.version + " side: " + square.getSide()
                    + ", area: " + square.getArea() + "m^2"
                    + ", perimeter: " + square.getPerimeter() + "m"
            );
        }

        private static void print(Printable printable) {
            System.out.println(printable.print());
        }
    }
